baseurl: "" # the subpath of your site, e.g. /blog
domain: my-site.github.io
url: https://my-site.github.io

include:
  - _pages

collections:
  projects:
    output: true
    permalink: /:collection/:name
    sort_by: date

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      stylesheets:
        - project
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
